spring:
    application:
        name: transactiondata
    boot:
        admin:
            client:
                url: http://localhost:8091
    data:
        mongodb:
            uri: mongodb://developer:Develop3r@localhost:27017/ginormitron
    kafka:
        bootstrap-servers: localhost:9092
        consumer:
            group-id: "transactions-group"

server:
    port: 8082

kafka-topics:
    replicaCount: 1
    partitionCount: 3
    names:
        customers: customers
        retailers: retailers
        transactions: transactions

management:
    endpoints:
        web.exposure.include: '*'
    info:
        env.enabled: true
