spring:
    data:
        mongodb:
            uri: mongodb://developer:Develop3r@localhost:27017/ginormitron
    kafka:
        bootstrap-servers: localhost:9092
        consumer:
            group-id: "transactions-group"

kafka-topics:
    replicaCount: 1
    partitionCount: 3
    names:
        customers: customers
        retailers: retailers
        transactions: transactions
