spring:
    application:
        name: customerdata
    boot:
        admin:
            client:
                url: http://localhost:8091
    kafka:
        bootstrap-servers: localhost:9092

server:
    port: 8080

kafka-topics:
    replicaCount: 1
    partitionCount: 3
    names:
        customers: customers

management:
    endpoints:
        web.exposure.include: '*'
    info:
        env.enabled: true
