spring:
    kafka:
        bootstrap-servers: localhost:9092

server:
    port: 8083

customer-data:
    url: localhost:8080

kafka-topics:
    replicaCount: 1
    partitionCount: 3
    names:
        retailers: retailers
