spring:
    application:
        name: retailerdata
    boot:
        admin:
            client:
                url: http://localhost:8091
    kafka:
        bootstrap-servers: localhost:9092

server:
    port: 8081

customer-data:
    url: localhost:8080

kafka-topics:
    replicaCount: 1
    partitionCount: 3
    names:
        retailers: retailers

management:
    endpoints:
        web.exposure.include: '*'
    info:
        env.enabled: true
