spring:
    kafka:
        bootstrap-servers: localhost:9092

server:
    port: 8081

customer-data:
    url: http://localhost:8080/api/v1

kafka-topics:
    replicaCount: 1
    partitionCount: 3
    names:
        retailers: retailers
